### ISSUE TITLE
Preparations to launch

### ISSUE THREAD

**Issue by achow101** [achow101/btcinformation.org#1]
Some TODOs, update as new ones thought up and old ones completed.

- [x] Get a domain and rename everything from bitcoin.org to domain or "we"
- [x] Remove Bitcoin Core sub site, downloads page, and related documentation
- [x] Remove tracking
- [x] Remove Paxful sponsorship
- [x] Disable donations
- [x] Disable translations
- [x] Find hosting
- [x] Remove Events page
- [x] Revert redesign
- [x] `git grep FIXME  # some quick stuff that needs to be updated prior to launch`
- [x] Blog post about fork

**Comment by harding** [comment]
A static site requires practically no memory or CPU, so any VPS with a good bandwidth plan ought to do, especially if you just plan to use a Let's Encrypt certificate.

Back when Bitcoin.org used secure hosting, we built the site on one $5/month VPS and rsync'd the built files to hosting directory on the most expensive production server.  By ensuring CGI was disabled, that meant nothing in the repository or generated by it would get executed on the production server, reducing the risk of things like IP-address-targetted file serving that would be hard to detect from an external audit.

Edit: it might be unclear that above was secure because you can configure ssh to only allow certain remote machines/keys to run certain commands.  So it was possible to configure the production server to only allow rsync to be called with the parameters that updated a certain directory and nowhere else on the filesystem.

**Comment by achow101** [comment]
I was actually thinking of just hosting the static site using github pages and have a cheap vps somewhere that builds it with every commit to the main source. It would then push the built stuff in a commit to the repo with the site.That way what is built is also auditable. I have a similar set up for docs.bitcoin.achow101.com

**Comment by harding** [comment]
That works, and it's how Bitcoin.org was hosted for about a year in 2013 before it got its own dedicated server for the security of the binaries.

**Comment by achow101** [comment]
I will be using the domain btcinformation.org. Feel free to redirect any other domains to the site as well.

**Comment by achow101** [comment]
Site is now live
