### ISSUE TITLE
[Feature request]: Put in place processes to ensure the website represents the community.

### ISSUE THREAD

**Issue by kek-coin** [achow101/btcinformation.org#14]
### Motivation
For this website to become a trustworthy source of information, it is necessary to ensure the processes through which it is updated are transparent and verifiable. Making sure the only path to change anything about the website goes through community review, and providing independently runnable automated checks on this process being bypassed would be great steps forward. The below checklist outlines my thoughts on how to implement this.

### Proposal
* [ ] Make the PR review process explicit and make sure it is adhered to rigidly to ensure that the latest version of the repository always has community approval.
* [x] Make the process of turning website source into pages deterministic so that others can replicate it and confirm no stuff has been sneakily put straight into the pages. (Fixed in #17).
* [x] Provide cross-platform instructions for deterministic building to lower the barrier of entry for people to verify the above point. (Fixed in #18, assuming the Ubuntu instructions work in WSL)
* [x] Host a file in the pages repo with hashes of all the pages to ease automation of independent verification that the website actually serves the last version of the pages repo. ([Already exists](https://github.com/achow101/btcinformation.org/blob/gh-pages/sha256sums.txt)).

Feedback on and review of this proposal is very welcome.

**Comment by achow101** [comment]
The site is currently built using this build script: https://github.com/achow101/btcinformation.org/blob/master/_build/update_site.sh (with a few extra lines to commit and push it to the gh-pages branch). The only actual build step is the `make deployment` call which can be done independently by anyone. AFAICT, the build is mostly deterministic. The only non-determinism is that timestamps are added to images and css files for some reason. I will look into it and see if I can make the build completely deterministic.

**Comment by harding** [comment]
In 2015 (when I was last really active developing for Bitcoin.org), we got the builds almost entirely deterministic.  This wasn't done for security (more about that later) but rather just to increase the speed of development by making it easier to diff HTML and to speed up debugging of the live site (which was hosted on a server had security measures that made it hard to access directly).  One artifact of that is the sha256sums file you've already discovered, which was meant to be used with a target in the Makefile to identify differences between your local build and the live site.  E.g.:

    make manual-check-diff-sha256sums

Unfortunately, this is currently broken because of a "cache-bursting" technique that was implemented on Bitcoin.org.  I think we can remove that.

```diff
-<link rel="stylesheet" href="/css/main.css?1533436396">
+<link rel="stylesheet" href="/css/main.css?1533580011">
```
However, I don't think any of these protections (except the explicit PR process) because the webserver can always server different pages to targeted users.  E.g., if it knows my IP address, it can serve me the honest page but serve random users (maybe 1-in-100) a dishonest page.

**Comment by achow101** [comment]
> However, I don't think any of these protections (except the explicit PR process) because the webserver can always server different pages to targeted users. E.g., if it knows my IP address, it can serve me the honest page but serve random users (maybe 1-in-100) a dishonest page.

While possible, I don't think this is much of a risk as we use github pages to host the website. Users can verify that it is indeed github pages by checking the DNS records.

**Comment by harding** [comment]
@achow101 Which just means that anyone at GitHub or their optimization/attack-prevention provider Cloudflare can serve up arbitrary content.  :-)

I admit that this is much less of an issue than it was on Bitcoin.org when Bitcoin Core binaries were being served, but I still think this means that deterministic builds don't provide the ideal level of security.  However, they are great for debugging, so I'm fully on board with enabling them again.

I don't know exactly what to do for the first checkbox about PR process.  IMO, a good process needs to be fast and lightweight for things like bug fixes but slow are careful for major issues.  Projects that have those attributes, in my experience, just have good maintainers who want to keep the community on board rather than lots of policy telling them what to do.

**Comment by kek-coin** [comment]
Evil hosting selectively serving honest files to some and not others is a problem, indeed, but making it easy for people to verify the contents should hopefully frustrate this. It also seems to me that the technical improvements are relatively low effort, and potentially carry additional benefits (deterministic builds are good for debugging, having a portable build environment makes recovery from hardware failure easier for the maintainers, etc).

As for the PR review point, that is probably the most difficult, as it is a social/coordination problem, not a technical one, but imho some low-hanging fruit could be easily codified into policy, such as "no direct pushing to master" (I am more familiar with gitlab, but there you have settings to prevent it entirely even by project members to make sure it doesn't happen by accident).

It makes sense to differentiate between content changes and functional changes, as these need different types of review, but perhaps the level of review needed is best judged on a case-by-case basis (low for trivial bug- and spelling-fixes, high for entirely new text or functionality).

**Comment by achow101** [comment]
With #17, points 2 and 3 are addressed. The site will be determinisitcally built (point 2) using the `make deployment` command (point 3).

For point 1, we can enforce some of the things via GitHub's [branch protection feature](https://help.github.com/articles/about-protected-branches/). These can be setup so that commits can only be pushed to the master branch if and only if certain conditions are met. This screenshot: 
![image](https://user-images.githubusercontent.com/3782274/43741731-3d52392a-9984-11e8-8475-23fc71693d1c.png)
shows the protections that are currently enabled for the master branch. Unfortunately this information is not visible to most people, only to administrators of the repository. Fortunately, you can see some of this information using the [GitHub API endpoint for the master branch](https://api.github.com/repos/achow101/btcinformation.org/branches/master).

**Comment by kek-coin** [comment]
@achow101 Awesome :). For my understanding, how does this address point 3? To clarify, with "portable" I mean a setup that can easily be run by anyone on any machine, regardless of OS.

**Comment by achow101** [comment]
For point 3, the `make deployment` command can be run on any machine that has make, ruby and [bundler](https://bundler.io/) installed. AFAIK, it doesn't rely on any specific OS things or any compiler things that may be OS specific.

**Comment by kek-coin** [comment]
Right now I am not finding any instructions for how to set up for local builds on e.g. Windows or OSX, though Windows users could use the linux subsystem and I suspect the instructions to be mostly portable to OSX. I am not able to verify these things, though, so I am hesitant to mark it as complete until someone with those systems confirms that they were able to reproduce the gh-pages following the instructions found [here](https://github.com/achow101/btcinformation.org/blob/master/docs/setting-up-your-environment.md).

**Comment by emmonspired** [comment]
Added PR to include notes on Mac build dependencies and environmental requirements: https://github.com/achow101/btcinformation.org/pull/18

**Comment by achow101** [comment]
Regarding point 1, I disabled the required signed commits branch protection feature because that requires all commits (not just the merges) to be signed. I think that it is unreasonable to force all contributors to GPG sign their commits, especially when many of them (especially new ones) don't know how and because rebasing and squashing commits can be annoying when the commits must be signed.

**Comment by emmonspired** [comment]
On that note, I think I'm going to blog about how to get GPG signing working. It was definitely a little learning curve. I've been using git for almost a decade, and never needed to sign anything on corporate projects, so if nothing else learned something along the way.

**Comment by vinniefalco** [comment]
Just wondering, why doesn't this use straight Jekyll? Then anyone who forks it and submits a pull request will have an automatic preview that anyone can view through the GitHub Pages mechanism (the content should be in a branch called **gh-pages**).

Is Jekyll missing anything that is required by the current site builder?

**Comment by harding** [comment]
@vinniefalco this site does use straight Jekyll, I think you meant GitHub pages (which is a superset of Jekyll).  :-)

The reason we don't use GitHub pages is because they don't allow custom plugins and we have quite a few custom plugins for things like translations (albeit not currently enabled), the developer documentation, the wallets, and some special QA functions that print warnings or abort builds to prevent certain errors from propagating to the live site.  You can see all the plugins in the `_plugins/` directory.

Some of the stuff done by our plugins predates features available in more recent versions of Jekyll.  I've refactored out some of that stuff over the years and we're probably due for another refactoring, but I don't see any easy path to making the site plugin-free (especially not if we plan to reimplement translations using the old mechanism, as I once tried to refactor out that plugin but failed to find a way to do it without major architectural changes to the site---which sucks because it's also our slowest plugin and is partially incompatible with fast incremental rebuilds for developer previews).

**Comment by vinniefalco** [comment]
> custom plugins

Oh, I see what you mean. I completely forgot about the translations (good job on that by the way). I've really been enjoying the Jekyll integration on GitHub pages, it has spared me from the need to deploy my own applications for my admittedly simple websites (which have a few blogs on them).

**Comment by achow101** [comment]
This project is no longer being maintained.
