### ISSUE TITLE
[brainstorming] refactoring developer documentation

### ISSUE THREAD

**Issue by karelbilek** [achow101/btcinformation.org#23]
Developer documentation on here / bitcoin.org (basically the same at this point) is pretty.... chaotic.

It has some good information, but also some outdated information, and is not very readable, since it is just one very long page.

You also have to consider that the RPC calls are now on bitcoin.org and don't make that much sense here, if (when? :)) the bitcoincore RPC docs is better formatted.

Also: there are some information missing, that are written well on bitcoin wiki, and vice versa.

I am thinking of somehow reorganizing the docs here... so far this is just a brainstorming issue, if you think this is a worthwhile goal, if it is worth time spent, etc.

Cc @harding :)

**Comment by karelbilek** [comment]
For example - one of the things I would do almost immediately is to break the long articles into separate articles.

https://btcinformation.org/en/developer-reference

This is very hard to read and very.... how to say. "Claustrophobic"?

**Comment by karelbilek** [comment]
Also (brainstorming) - should this developer reference keep living here, on btcinformation, or be moved to bitcoincore.org?

**Comment by harding** [comment]
1. I'm 100% in support of breaking them up into multiple pages.  This was a highly-discussed issue during their initial design in Feb 2014, and we (Saivann Carignan, Gregory Sanders, and myself) we unable to come to complete agreement, so we decided to choose one method to start with (big pages) but store the information in the repository in a format that could easily support both big and small pages, (e.g. each section is split into a separate source file).  By taking advantages available in newer versions of Jekyll than the 1.x series we initially used (e.g. collections), it should be only take an afternoon's work to do a basic split of the documentation into multiple pages.

    The primary reason I haven't done that is that I'm lazy.  The secondary reason is because it's seems to me that a priority should be given to bringing the docs up to date before splitting them.  But the tertiary reason is more interesting: it's also been requested that we also provide the documentation in ebook format (e.g. epub, pdf, mobi/kindle); there seems that there'd be significant overlap between splitting files into separate pages and splitting them into chapters, so I wanted to do both at the same time.

2. I seem to be in the minority here, but I don't like the idea of moving documentation to BitcoinCore.org unless it's Bitcoin Core specific.  E.g. documentation about consensus systems, the P2P protocol, wallets, and most other stuff seems to me to be general Bitcoin information even if Bitcoin Core contributors are often leading the initiative in developing improvements to some of those systems.

    Before this site was created, I had planned that if I ever did a major refresh of the documentation, I'd move it off Bitcoin.org to a separate developer-documentation-only site.  However, I don't think that's necessary now, so BtcInformation.org seems as good as any site.  (But I'm not currently focused on dev docs, so if you are, you obviously should have the say in where you want to contribute.)

3. I support removing RPC docs from this site.  If we were removing them from Bitcoin.org, I'd want to spend some time thinking about clever ways to redirect people from particular entries to the corresponding BitcoinCore.org entries, as several people (not the least me) have linked to those Bitcoin.org RPC entries many times over the years.  However, this site doesn't have many backlinks (if any to the RPCs), so outright breaking them seems fine to me.

Out of of a somewhat masochistic curiosity, can you point to any Bitcoin Wiki pages that you think are better written than this documentation?  As a technical writer, I'm often comparing my work to that of other technical writers and trying to do better than them, at least for my own amusement.  :-)

Finally, in case it isn't obvious, I strongly support breathing fresh life into these documents that have been almost unchanged since Sept 2015.

**Comment by karelbilek** [comment]
ad 1

I don't feel that confident to refresh the docs :) so I won't do that. I can help with splitting and reorganization.

ad 2

OK. I will take it as btcinformation is a new site when I can go wild with experimenting and making big PRs :D 

ad note: 

I like for example this article about basic transactions

https://en.bitcoin.it/wiki/Transaction

But it is heavily outdated. I also used to learn about script in this article - but yeah it is just a big table

https://en.bitcoin.it/wiki/Script

----

as for why I started this issue - I sometimes forget the basic BTC terminology when I don't work with bitcoin for a while, so today I googled "sighash" (to remind myself what does it mean exactly again...) and I found only bitcoin.org docs. And I was visually lost on the page. So I thought that if there is this "fresh slate" fork, I can make some wilder changes :D

**Comment by harding** [comment]
I know @achow101 is also interested in good maintenance of the dev docs, so I'd suggest waiting for him to chime in before putting in to much work.  That said, if he agrees with splitting the dev docs into smaller pages, I suggest we focus this issue on that work.

Here's how I suggest proceeding:

1. Make sure the version of Jekyll we use supports collections; also make sure we have an adequete version of the Jekyll pagintation plugin to handle Next Chapter and Last Chapter buttons on the pages (or we make our own Liquid template/plugin).

2. Put each chapter into a separate page in the collection using `{% include %}` the same as the current giant pages do.  This has the notable advantage that we keep the source files exactly where they are so we can easily continue to merge in changes made upstream (sidestream?) from Bitcoin.org.  It also means that, at least initially, we can have the single pages and the split pages coexisting on the site side-by-side until we're convinced one is better than the other.

3. Figure out how to generate the table of contents across the full collection.  Collections should make this easy, and I think you've already worked with them enough via the RPC docs on BitcoinCore.org that I don't need to say more here.

4. Update links to point to the correct pages.  This is probably the bulk of the work and the part that could be really boring unless you find a way to automate the change.  On the upside, internal links are CI tested, so whoever does this work doesn't have to worry about breaking things (that's always a comfort to me when I'm doing things, which is why almost all the tests on this site were written by me).

Then we put up a preview and see how it looks.  This can probably actually be done before step 4 so that only a mild amount of work is lost if it turns out to be unnavigable or otherwise flawed.

**Comment by achow101** [comment]
This project is no longer being maintained.
